# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/ak-birthday" # the subpath of your site, e.g. /blog/
url: "https://prajwal-y.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
